const ActionTypes = {
    FETCH_USERS_START: 'FETCH_USERS_START',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FILTER_CAMPAIGNS: 'FILTER_CAMPAIGNS',
    ADD_CAMPAIGN: 'ADD_CAMPAIGN',
    FILTER_CAMPAIGNS_BY_DATE: 'FILTER_CAMPAINGS_BY_DATE',
    ADD_CAMPAIGN_ERROR: 'ADD_CAMPAIGN_ERROR'
};

export default ActionTypes;